### ISSUE TITLE
"inform a roadmap", what's the meaning?

### ISSUE THREAD

**Issue by rsimai** [OpenStackweb/openstack-org#126]
https://github.com/OpenStackweb/openstack-org/blob/5abd58164b7b5255861475df7d0681bef04a4585/survey_builder/templates/Layout/Surveys_LandingPage.ss#L39

I don't get the meaning of "OpenStack users share their opinions and deployment choices to inform the roadmap", hence wouldn't know how to translate it. What's meant by "inform a roadmap"?

**Comment by jimmytipit** [comment]
It's in reference to the roadmap of the latest software release (https://www.openstack.org/software/roadmap/).  We actually since updated that text to "
See the OpenStack community’s opinions, adoption and technology choices", which you can see here: https://www.openstack.org/user-survey/survey-2019/landing
