### ISSUE TITLE
summit schedule app should offer iCal (ics) feed

### ISSUE THREAD

**Issue by aspiers** [OpenStackweb/openstack-org#133]
I know the calendar syncing feature is popular with some people, but (sorry) I would like to suggest an alternative approach for ~~five~~ four reasons:

- Some people really don't like giving third-party programs access to their main calendar, not just due to privacy concerns, but also the worry that it might accidentally delete existing events.  If a bug deleted even one or two events in my calendar, it could easily turn into a catastrophe. 
- The current approach requires repeated syncing when events are added/removed.
- ~~The current approach only allows sharing your summit schedule with your colleagues if the calendar system you sync with supports this.~~
- The current approach only works for people who use one of three proprietary calendaring systems (Google, iCloud, and Outlook).  It doesn't work with any open source calendaring system.
- ~~It's cleaner if OpenStack events are provided in a separate calendar, since then any modern calendar client can simply toggle viewing them on or off.~~
- I suspect it would make the code a lot simpler and more reliable if it adopted the alternate approach, since it only has to write a file which is served over https, rather than implement syncing with multiple calendar services.

So what alternative am I suggesting?  It's very simple, and solves all of the above issues: export an [iCalendar](https://tools.ietf.org/html/rfc5545) feed over https.  This is a standard approach which in fact is even [already adopted by the OpenStack community for IRC meetings](http://eavesdrop.openstack.org/).

**Comment by smarcet** [comment]
RE**:It's cleaner if OpenStack events are provided in a separate calendar, since then any modern calendar client can simply toggle viewing them on or off.**
this is already working on that way, i mean calendar sync create a separate calendar using the current summit name

**Comment by aspiers** [comment]
Oh yeah, my bad - for some reason I thought it added them to the main calendar.  Still, a good general security principle to follow is never to require more privileges than you need, and there is no need to require any privileges here, since publishing an iCalendar feed doesn't require any.

**Comment by smarcet** [comment]
re:
**The current approach only allows sharing your summit schedule with your colleagues if the calendar system you sync with supports this.**

on icloud calendar you could share the the calendar making it public, on google calendar your could share it on calendar settings -> Access permissions -> Make available to public

on outlook calendar i suspect that you could do the same, but need to double check

re: 
**Some people really don't like giving third-party programs access to their main calendar, not just due to privacy concerns, but also the worry that it might accidentally delete existing events. If a bug deleted even one or two events in my calendar, it could easily turn into a catastrophe.**

the privacy concerns that you  are expressing are listed once that your agree giving permission to the sync app using OAuth2 ( there is a consent page where the user see the permissions that he/she is granting to the sync app) , this is for google and outlook calendar, for icloud calendar, i agree that is not so transparent bc its requiring an app password but its the way that apple provides auth/authz to its ical server (https://support.apple.com/en-us/HT204397), as you may read there, that is the way that they use to add ical synching with third party apps like thunderbird , probably for this case would be convenient to express which operations the sync app is performing through code so the user is aware of the permissions granted on this particular case and its more transparent. and i do understand your concern, but the sync app only operates on the events created for the particular calendar created per summit, so its not operate on your main calendar or other calendar but the one created specifically for the summit and synching purposes

cheers

**Comment by aspiers** [comment]
Thanks a lot for the reply.  Firstly I want to emphasise I don't mean to sound ungrateful and I'm not complaining about anything here.  I just want to explain why I think there is a better way to provide this calendar integration functionality.  Details below:

[**@smarcet**](https://github.com/smarcet) commented on [17 Nov 2018, 16:49 GMT](https://github.com/OpenStackweb/openstack-org/issues/133#issuecomment-439630613 "2018-11-17T16:49:27Z - Replied by Github Reply Comments"):
> re:  
> 
> **The current approach only allows sharing your summit schedule with your colleagues if the calendar system you sync with supports this.**
> 
> on icloud calendar you could share the the calendar making it public, on google calendar your could share it on calendar settings -&gt; Access permissions -&gt; Make available to public
> 
> on outlook calendar i suspect that you could do the same, but need to double check

OK sorry you're right, so I was saying the wrong thing; I'll update my list above to fix this inaccuracy.  The point is that this syncing approach is limited to three calendaring solutions: Google, iCloud, and Outlook (which incidentally are all proprietary and against the spirit of OpenStack's Four Opens).  If you don't use any of these then you can't sync your summit schedule with your calendar.  It would be much nicer if people weren't discriminated against for using open source calendaring solutions.

> re:  
> 
> **Some people really don't like giving third-party programs access to their main calendar, not just due to privacy concerns, but also the worry that it might accidentally delete existing events. If a bug deleted even one or two events in my calendar, it could easily turn into a catastrophe.**
> 
> the privacy concerns that you  are expressing are listed once that your agree giving permission to the sync app using OAuth2 ( there is a consent page where the user see the permissions that he/she is granting to the sync app) , this is for google and outlook calendar, for icloud calendar, i agree that is not so transparent bc its requiring an app password but its the way that apple provides auth/authz to its ical server ([support.apple.com/en-us/HT204397](https://support.apple.com/en-us/HT204397))
> as you may read there, that is the way that they use to add ical synching with third party apps like thunderbird , probably for this case would be convenient to express which operations the sync app is performing through code so the user is aware of the permissions granted on this particular case and its more transparent.

Sorry, I don't mean to sound awkward but this is not the point.  I'm not talking about a lack of transparency in what users have to agree to in order to get the syncing functionality.  I'm talking about the fact that it is *mandatorily required* in order to get that functionality, even though technically it is completely unnecessary because the same thing could be achieved just by publishing an ics feed.

> and i do understand your concern, but the sync app only operates on the events created for the particular calendar created per summit, so its not operate on your main calendar nor other calendar but the one created specifically for the summit and synching purposes

Again that's not the point, sorry.

I have no reason to doubt that what you say is true, and I'm very sure that the intention of any developers to make this syncing reliable and secure is 100% bona fide, because in my experience every single person I have met in the OpenStack community is super awesome ;-)  But ...

Even in that case bugs could happen and accidentally wipe events from our calendars.  Your statement above cannot be verified by users, so effectively you are asking the users to trust that the developers are *both* 100% trustworthy *and* have not accidentally implemented some buggy behaviour.  Yes it's probably quite unlikely that any bug would appear which would cause destructive operations on people's calendars, but the point is that the app should not be forcing users to accept that risk in the first place, especially given that it is technically unnecessary due to a viable alternative.  Even if the source code to the web application is open (and I know [it is](https://github.com/OpenStackweb/openstack-org/blob/master/summit/code/controllers/CalendarSyncController.php)), there's still no guarantee that the code on GitHub exactly matches what is deployed on the website.  So this approach also requires users to trust not just the robustness of the code but also of the deployment mechanism (which they have no way to audit).  For example even if the code is 100% reliable, there is a man-in-the-middle attack on the deployment technique.  Therefore a successful attacker could potentially gain access to hundreds or maybe even thousands of calendaring accounts in one go.

Good security models never require more permissions or trust than they need.  Publishing an ics feed requires zero extra permissions or trust from the user, plus it's surely much easier to implement, and would work with any standards-compliant calendaring system.  So it would be great if you considered implementing this!  Again thanks a lot for listening :-)

**Comment by jimmytipit** [comment]
@aspiers Thanks for the detailed discussion! I've discussed this with @smarcet and we agree that an ics feed is a solid addition to the calendar management options. That said, we have had VERY positive feedback from the community around the sync feature and it's something we'll be keeping regardless.  An ics feed should give those with security concerns and alternate way to manage their calendar, while those that prefer the sync would still maintain that option.  Of course, all the code is open source, so if there is a larger concern about security, the community is welcome to review and make pull requests.

Cheers,
Jimmy

**Comment by aspiers** [comment]
Thanks a lot @jimmytipit and @smarcet for listening to my suggestion!  Yes I totally agree that bearing in mind the fact that people are already enjoying the existing sync feature, it makes no sense to remove it.  Having a choice of two options for calendar integration would be super awesome :)

**Comment by smarcet** [comment]
ok this is release here https://www.openstack.org/summit/denver-2019/summit-schedule
you should be log in order to see a new option "GET SHAREABLE CALENDAR LINK"

check screen caps


<img width="1252" alt="Screen Shot 2019-04-09 at 1 50 26 PM" src="https://user-images.githubusercontent.com/2577122/55819274-cff1bd80-5ace-11e9-8562-4e697d4bb482.png">
<img width="942" alt="Screen Shot 2019-04-09 at 1 50 33 PM" src="https://user-images.githubusercontent.com/2577122/55819278-d2ecae00-5ace-11e9-9acc-131e9d735520.png">

regards

**Comment by aspiers** [comment]
This is fantastic, thank you so much!
